
POST http://localhost:9000/api/login
Content-Type: application/json

{
    "username": "s",
    "password": "s"
}

### 
POST http://localhost:9000/api/authentication
Content-Type: : application/json,
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InMiLCJpYXQiOjE3MTMyNjk0NzR9.2Xe47ztZ0JvbyIinad4mSZnHodu66_6539QxACZJhEA   

{
    "username": "a",
    "password": "s"
}